fix: compose update na pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -19,7 +19,12 @@ jobs:
     - name: Copy .env
       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
     - name: Install Dependencies
-      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
+      run: |
+        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
+        if [ $? -ne 0 ]; then
+          echo "Composer install failed. Running composer update."
+          composer update -q --no-ansi --no-interaction --no-progress --prefer-dist
+        fi
     - name: Generate key
       run: php artisan key:generate
     - name: Directory Permissions
